#!/bin/bash
# SPDX-License-Identifier: Apache-2.0

# usage: run_test test_name checkscript.sh input.sv
printf "TEST: %s\n" "$1"

actual_file=out/"$1"/sv-bugpoint-combined.sv
[ -e "$actual_file" ] && rm "$actual_file" # to not get fake PASS if bugpoint did not overwrite old result
golden_file=golden/"$1"/sv-bugpoint-combined.sv

OUT_DIR=out/"$1"
shift
TEST_SCRIPT="$1"
shift

bugpoint_msg=$(sv-bugpoint "${OUT_DIR}" "${TEST_SCRIPT}" "$@" --force 2>&1) || (printf "%s\n" "$bugpoint_msg" >&2; exit 1)

diff "$golden_file" "$actual_file" --color=always >&2

EXIT_CODE=$?

[ "$EXIT_CODE" -eq 0 ] && printf "PASSED\n\n" || printf "FAILED\n\n"
GOLDEN="${GOLDEN:-}"
if [ -n "$GOLDEN" ]; then
  mkdir -p "$(dirname "$golden_file")"
  cp "$actual_file" "$golden_file"
fi

exit $EXIT_CODE
